namespace Microsoft.Azure.SignalR.Test.Server;

public class LongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongNameChatLongName : Chat
{
}
